### ISSUE TITLE
There is no favicon; here is corgi

### ISSUE THREAD

**Issue by Hugo14453** [lmas/ss13_se#1]
It's just Ian centred and downsized to 32x32
https://i.imgur.com/LEADrWQ.png

**Comment by lmas** [comment]
Hey thanks! Much appreciated. Did you take it from the game? Think you could make it into a .ico file with transparent background too?

**Comment by Hugo14453** [comment]
I can make it transparent yet, gimme a few minutes

**Comment by Hugo14453** [comment]
ok, here it is transparent background .ico file
http://www.mediafire.com/download/a2utltqybfi6gww/LEADrWQ.ico

**Comment by lmas** [comment]
Alright! 

Thanks for you kind words, it's great to hear it's usefull to someone else besides myself.
