### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by EMT321** [lmas/ss13_se#3]
Hello, the site seems to be down. Is this still operational?

**Comment by EMT321** [comment]
@lmas

**Comment by lmas** [comment]
Hi, sorry but I have a lack of interest and free time to maintain this old beast so I decided to pull the plug for now.

The old python code hasn't been updated for years and it seems that I never manage to finish the big rewrite (using Go instead). The old code was also hogging the resources on my tiny server and possibly exposing a security hole or two.

Although I haven't decided 100% yet if I should give up making that rewrite...
